on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
        working-directory: ./packages/api
      - name: Run tests
        run: npm test
        working-directory: ./packages/api
      - name: Check schema vs. production
        run: echo "Checking GraphQL schema vs. production... yes good."
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo building
      - run: sleep 3
      - run: echo built
      - run: sleep 3
      - run: echo zipped
      - run: sleep 3
      # echo commit sha
      - run: echo pushing zip to s3/bucket/api/$GITHUB_SHA.zip
