on:
  workflow_call:
    inputs:
      targetEnv:
        type: string
        required: true
        description: "The environment to deploy to"
      targetSlackChannelId:
        type: string
        required: true
        description: "The Slack channel ID to post to"
      targetSlackThreadTs:
        type: string
        required: true
        description: "The Slack thread ID to post to"
    outputs:
      ranMigrations:
        description: "Whether or not migrations were run"
        value: ${{ jobs.run_migrations.outputs.changed }}
    secrets:
      slackBotToken:
        description: "The Slack bot token"
        required: true

jobs:
  run_migrations:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.check_for_changes.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Check for changes
        id: check_for_changes
        run: |
          if git diff --quiet HEAD^ HEAD -- ./packages/api/migrations; then
            echo "No changes in /packages/api/migrations"
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Changes detected in /packages/api/migrations"
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
      - name: Update Slack about running migrations
        if: steps.check_for_changes.outputs.changed == 'true'
        uses: ArnaudRinquin/slack-github-action@thread_ts
        with:
          thread-ts: ${{ inputs.targetSlackThreadTs }}
          channel-id: "${{ inputs.targetSlackChannelId }}"
          payload: |
            {
              "text": "New migrations detected... running them 🔄"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slackBotToken }}
      - name: Update Slack about skipping migrations
        if: steps.check_for_changes.outputs.changed == 'false'
        uses: ArnaudRinquin/slack-github-action@thread_ts
        with:
          thread-ts: ${{ inputs.targetSlackThreadTs }}
          channel-id: "${{ inputs.targetSlackChannelId }}"
          payload: |
            {
              "text": "No new migrations detected... skipping ⏭️"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slackBotToken }}

      - name: Actually execute the migrations
        if: steps.check_for_changes.outputs.changed == 'true'
        run: |
          echo "Running migrations..."
          sleep 10
          echo "Migrations complete."
        working-directory: ./packages/api
      - name: Update slack thread about migrations completion
        if: steps.check_for_changes.outputs.changed == 'true'
        uses: ArnaudRinquin/slack-github-action@thread_ts
        with:
          thread-ts: ${{ inputs.targetSlackThreadTs }}
          channel-id: "${{ inputs.targetSlackChannelId }}"
          payload: |
            {
              "text": "Migrations complete! ✅"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slackBotToken }}

      - name: Update slack thread about migration failure
        if: failure()
        uses: ArnaudRinquin/slack-github-action@thread_ts
        with:
          thread-ts: ${{ inputs.targetSlackThreadTs }}
          channel-id: "${{ inputs.targetSlackChannelId }}"
          payload: |
            {
              "text": "Migrations failed! 🚩🚩🚩"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slackBotToken }}
